version: '3.9'
services:
  backend:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn code.main:app --reload --host 0.0.0.0
    env_file: .env
    restart: always
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
